-intstyle "ise" -incremental -o "C:/Users/Elsik/Desktop/DYPLOM/Freq_constant/instrument_tb_isim_beh.exe" -prj "C:/Users/Elsik/Desktop/DYPLOM/Freq_constant/instrument_tb_beh.prj" "work.instrument_tb" 
